### ISSUE TITLE
Virtual Office Hours

### ISSUE THREAD

**Issue by chris-prener** [slu-soc5050/Core-Documents#1]
Hi team,
I am going to use GitHub Issues for a second purpose. If you have a question, figure out a trick for doing something that you want to share, or find a good resource for something, please use the Issues section of the Core-Documents repository. When you post there, include a mention for the whole class in your post. To do that, use this handle -  @slu-soc5050/allclass .

My experience with graduate classes is that it can be difficult to get people together to work collaboratively because of the packed schedules that folks often have. Hopefully this works out as a way to touch base with the rest of the class.

cheers,
@chris-prener

**Comment by tesarigel** [comment]
Hi @chris-prener ,
I don't know if you put up the videos yet, but neither they (nor your class) are listed on my Tegrity page. Even stranger, I am supposed to be doing something with a sandbox? What is that about?
Thanks, 
Tesa

**Comment by chris-prener** [comment]
Hi @tesarigel ,
Interesting. It may be because you are auditing? Try this link: https://slu.tegrity.com/#/recording/1ee49a47-e56d-4c63-9d17-5d44a79fac40?playbackToken=P67015WHZLEJ

Let me know if that works...

**Comment by tesarigel** [comment]
I wondered about that, but I am still curious about the "sandbox course" listed on my tegrity page as potentially having videos, I guess that is out of your realm of expertise (lol). 

So the link worked, does it contain all three videos or just the dynamic documents? It looks short for all three. If not, do you mind sending me the other two as well?

Thanks for responding so quickly @chris-prener , hope you had a good holiday.

**Comment by chris-prener** [comment]
No worries @tesarigel . Had a great holiday! I've added links in the [Week 03 Jotter](https://github.com/slu-soc5050/Core-Documents/wiki/Week-03) to the other two videos that should work for you and @marypatholden .
