### ISSUE TITLE
need some help...

### ISSUE THREAD

**Issue by tesarigel** [slu-soc5050/Core-Documents#3]
So, I really am not understanding how to navigate Atom or GitHub desktop. I think I missed something crucial and I cannot find it in my notes or the slides. Do you have anytime tomorrow @chris-prener or maybe Taylor? The issues with navigation are really simple but they are preventing me from doing any of the statistics. Please let me know. Thanks.

**Comment by chris-prener** [comment]
Hi @tesarigel ,
If you have a specific question I can field it here today. Otherwise do you want to come by at 10:30am tomorrow?

cheers,
@chris-prener

**Comment by tesarigel** [comment]
I do have some specific questions, one about syncing - I think that I just need to be shown that from the beginning, maybe on the computer in the lab. And Atom, I am just not understanding how to even open a file window and find the different sections of the program :(, but I had the header issue as well even though I checked several times about the Stata language. I would just feel more comfortable with a demonstration so I will swing by at 10:30. It shouldn't take too long @chris-prener , thanks.

**Comment by chris-prener** [comment]
OK, that is fine. I'll see you tomorrow! @chris-prener
