### ISSUE TITLE
PS/Lab clarification

### ISSUE THREAD

**Issue by ruizp** [slu-soc5050/Core-Documents#4]
@chris-prener Hi Chris, in some of the questions for the PS/Labs, you ask use to run descriptive statistics on variables, and then talk about the "relevant statistics" (why we included them, and others not).  Can you please clarify what you mean by "relevant"? If I run a summarize, detail command I get many descriptive statistics.  Thanks!

Pedro

**Comment by chris-prener** [comment]
Hey @ruizp ,
Think back to weeks 1 and 2 and focus on level of measurement. For the given variable's level of measurement, what are the appropriate descriptive statistics?

@chris-prener
